//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackballScroll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackballScroll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About TrackballScroll.
        /// </summary>
        internal static string TextButtonAbout {
            get {
                return ResourceManager.GetString("TextButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default action (back, forward).
        /// </summary>
        internal static string TextButtonActionDefault {
            get {
                return ResourceManager.GetString("TextButtonActionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle-click.
        /// </summary>
        internal static string TextButtonActionMiddle {
            get {
                return ResourceManager.GetString("TextButtonActionMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to scroll.
        /// </summary>
        internal static string TextButtonActionNone {
            get {
                return ResourceManager.GetString("TextButtonActionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle scrolling.
        /// </summary>
        internal static string TextButtonActionToggle {
            get {
                return ResourceManager.GetString("TextButtonActionToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextButtonExit {
            get {
                return ResourceManager.GetString("TextButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string TextButtonHookEnabled {
            get {
                return ResourceManager.GetString("TextButtonHookEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default action (back, forward).
        /// </summary>
        internal static string TextButtonHookUseforDefault {
            get {
                return ResourceManager.GetString("TextButtonHookUseforDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle-click.
        /// </summary>
        internal static string TextButtonHookUseforMiddle {
            get {
                return ResourceManager.GetString("TextButtonHookUseforMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll key.
        /// </summary>
        internal static string TextButtonHookUseforScroll {
            get {
                return ResourceManager.GetString("TextButtonHookUseforScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer one axis movement.
        /// </summary>
        internal static string TextButtonPreferAxis {
            get {
                return ResourceManager.GetString("TextButtonPreferAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse horizontal movement.
        /// </summary>
        internal static string TextButtonReverseHorizontalScroll {
            get {
                return ResourceManager.GetString("TextButtonReverseHorizontalScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse verticall movement.
        /// </summary>
        internal static string TextButtonReverseVerticalScroll {
            get {
                return ResourceManager.GetString("TextButtonReverseVerticalScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll key secondary action.
        /// </summary>
        internal static string TextButtonScrollAction {
            get {
                return ResourceManager.GetString("TextButtonScrollAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll speed.
        /// </summary>
        internal static string TextButtonScrollSpeed {
            get {
                return ResourceManager.GetString("TextButtonScrollSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string TextButtonSpeedHigh {
            get {
                return ResourceManager.GetString("TextButtonSpeedHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string TextButtonSpeedLow {
            get {
                return ResourceManager.GetString("TextButtonSpeedLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string TextButtonSpeedMedium {
            get {
                return ResourceManager.GetString("TextButtonSpeedMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X1 button action.
        /// </summary>
        internal static string TextButtonX1Action {
            get {
                return ResourceManager.GetString("TextButtonX1Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X2 button action.
        /// </summary>
        internal static string TextButtonX2Action {
            get {
                return ResourceManager.GetString("TextButtonX2Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackballScroll Extended.
        /// </summary>
        internal static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
    }
}
